
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cava;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int AND = 17;
  public static final int IGUALIGUAL = 25;
  public static final int MENOR = 18;
  public static final int ELSE = 13;
  public static final int NOTEQ = 28;
  public static final int OR = 16;
  public static final int RPAREN = 3;
  public static final int IGUAL = 11;
  public static final int INT = 4;
  public static final int WHILE = 14;
  public static final int SUMA = 20;
  public static final int MAJOR = 19;
  public static final int RETURN = 15;
  public static final int TRUE = 22;
  public static final int IF = 12;
  public static final int LBRACKET = 29;
  public static final int LPAREN = 2;
  public static final int ID = 24;
  public static final int RBRACKET = 30;
  public static final int MENORIG = 27;
  public static final int RCOR = 7;
  public static final int NUM = 33;
  public static final int MAJORIG = 26;
  public static final int STRING_LITERAL = 32;
  public static final int BOOLEAN = 5;
  public static final int STRING = 31;
  public static final int COMA = 8;
  public static final int LCOR = 6;
  public static final int EOF = 0;
  public static final int FALSE = 23;
  public static final int CONST = 10;
  public static final int error = 1;
  public static final int PCOMA = 9;
  public static final int RESTA = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "INT",
  "BOOLEAN",
  "LCOR",
  "RCOR",
  "COMA",
  "PCOMA",
  "CONST",
  "IGUAL",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "OR",
  "AND",
  "MENOR",
  "MAJOR",
  "SUMA",
  "RESTA",
  "TRUE",
  "FALSE",
  "ID",
  "IGUALIGUAL",
  "MAJORIG",
  "MENORIG",
  "NOTEQ",
  "LBRACKET",
  "RBRACKET",
  "STRING",
  "STRING_LITERAL",
  "NUM"
  };
}

